#!/bin/bash

# Generate checked-in storage layout documentation files for upgradeable contracts.
set -euo pipefail

contracts=(
  # Add every implementation deployed behind an upgradeable proxy here.
  "src/impl/Shadow.sol:Shadow"
)

generate_layout_file() {
  local contract=$1
  local source_path="${contract%%:*}"
  local contract_name="${contract##*:}"

  if [ ! -f "$source_path" ]; then
    echo "Missing contract source: $source_path"
    return 1
  fi

  local source_dir="${source_path%/*}"
  local source_file="${source_path##*/}"
  local source_basename="${source_file%.sol}"
  local layout_path="${source_dir}/${source_basename}_Layout.sol"

  local inspect_output
  inspect_output=$(FORGE_DISPLAY=plain forge inspect "$contract" storagelayout 2>&1) || {
    echo "forge inspect failed for $contract"
    echo "$inspect_output"
    return 1
  }

  local layout_comments
  layout_comments=$(echo "$inspect_output" | awk -F'|' '
    NF >= 6 && /\|/ {
      for (i = 1; i <= NF; i++) gsub(/^[ \t]+|[ \t]+$/, "", $i);
      name = $2; type = $3; slot = $4; offset = $5; bytes = $6;

      if (name == "Name" || name == "" || slot == "Slot" || name ~ /^[-+]+$/) next;

      printf "//   %-30s | %-50s | Slot: %-4s | Offset: %-4s | Bytes: %-4s\n", \
        name, type, slot, offset, bytes;
    }
  ')

  if [ -z "$layout_comments" ]; then
    echo "No layout data found for $contract"
    return 1
  fi

  cat > "$layout_path" <<EOF
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.33;

/// @title ${contract_name}Layout
/// @notice Storage layout documentation for ${contract_name}.
/// @dev This file is auto-generated by script/gen-layouts.sh. DO NOT EDIT MANUALLY.
/// @custom:security-contact security@taiko.xyz

// solhint-disable max-line-length
${layout_comments}

abstract contract ${contract_name}Layout { }
EOF

  echo "Updated $layout_path"
}

for contract in "${contracts[@]}"; do
  generate_layout_file "$contract"
done
