// SPDX-License-Identifier: MIT
pragma solidity ^0.8.33;

/// @title ShadowLayout
/// @notice Storage layout documentation for Shadow.
/// @dev This file is auto-generated by script/gen-layouts.sh. DO NOT EDIT MANUALLY.
/// @custom:security-contact security@taiko.xyz

// solhint-disable max-line-length
//   _initialized                   | uint8                                              | Slot: 0    | Offset: 0    | Bytes: 1   
//   _initializing                  | bool                                               | Slot: 0    | Offset: 1    | Bytes: 1   
//   __gap                          | uint256[50]                                        | Slot: 1    | Offset: 0    | Bytes: 1600
//   _owner                         | address                                            | Slot: 51   | Offset: 0    | Bytes: 20  
//   __gap                          | uint256[49]                                        | Slot: 52   | Offset: 0    | Bytes: 1568
//   _pendingOwner                  | address                                            | Slot: 101  | Offset: 0    | Bytes: 20  
//   __gap                          | uint256[49]                                        | Slot: 102  | Offset: 0    | Bytes: 1568
//   __gap                          | uint256[50]                                        | Slot: 151  | Offset: 0    | Bytes: 1600
//   __gap                          | uint256[50]                                        | Slot: 201  | Offset: 0    | Bytes: 1600
//   _paused                        | bool                                               | Slot: 251  | Offset: 0    | Bytes: 1   
//   __gap                          | uint256[49]                                        | Slot: 252  | Offset: 0    | Bytes: 1568
//   _status                        | uint256                                            | Slot: 301  | Offset: 0    | Bytes: 32  
//   __gap                          | uint256[49]                                        | Slot: 302  | Offset: 0    | Bytes: 1568
//   _consumed                      | mapping(bytes32 => bool)                           | Slot: 351  | Offset: 0    | Bytes: 32  
//   __gap                          | uint256[49]                                        | Slot: 352  | Offset: 0    | Bytes: 1568
